config/routes.rb
MapEverything::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }, :path_prefix => 'd', :sign_out_via => [ :get, :post, :delete ]

  get '/feed' => 'features#feed',
    :as => :feed,
    :defaults => { :format => 'atom' },
    :show_unapproved => false

  get '/moderator_feed' => 'features#feed',
    :as => :moderator_feed,
    :defaults => { :format => 'atom' },
    :show_unapproved => true

  get 'features/map' => 'features#map', :as => 'map'
  match 'features/:id/toggle_like/:vote' => 'features#toggle_like'
  get 'features/:id/like_widget' => 'features#like_widget'
  resources :features do
  end

  resources :comments
  resources :users

  root :to => "features#map"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user

  attr_accessible :text

  validates :posted_on, :presence => true
  validates :text, :presence => true
  validates :user_id, :presence => true

  self.per_page = 10
end

app/controllers/comments_controller.rb
# encoding: utf-8

class CommentsController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :show]

  def index
    @comments = Comment.all
    respond_to do |format|
      format.json {render json: @comments}
      format.html
    end
  end

  def new
    @comment = Comment.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def show
    @comment = Comment.find(params[:id])
    respond_to do |format|
      format.json {render json: @comment}
    end
  end

  def create
    @comment = Comment.new(params[:comment])
    @comment.posted_on = DateTime.now;
    @comment.user = current_user

    if @comment.save
      flash[:notice] = t('comments.created')
    else
      flash[:alert] = t('comment.create_failed')
    end

    respond_to do |format|
      format.js
    end
  end

  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.json { head :no_content }
        format.js
      else
        flash[:alert] = t('comment.update_failed')
        format.json { render json: @comment.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment_id = @comment.id
    @comment.destroy

    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li class="comment" id="comment_<%= comment.id -%>">
<div class="comment-header">
  <div class="comment-author-datetime<%= ' by-admin' if comment.user.admin? -%>">
    <strong><%= comment.user.name %><%= ' (модератор)' if comment.user.admin? -%>:</strong><br/>
    <%= comment.posted_on.strftime("%d.%m.%Y %H:%M") %></div>
  <div class="comment-actions">
    <%= link_to 'Править', edit_comment_path(comment), :remote => true if user_signed_in? and current_user.admin? %>
    <%= link_to 'Удалить', comment, :method => :delete, :remote => true, :confirm => 'Вы действительно хотите удалить комментарий?' if user_signed_in? and current_user.admin? %>
  </div>
</div>
<div class="comment-text"><%= simple_format comment.text %></div>
</li>

app/views/comments/_form.html.erb
<div id="comment-notice"></div>
<%= form_for @comment, :remote => true do |f| %>
  <fieldset>
    <legend>Отправка комментария</legend>
  <p>
    <%= f.text_area :text, :rows => 2 %>
  </p>

  <p>
    <%= f.submit 'Отправить' %>
  </p>
</fieldset>
<% end %>

app/views/comments/create.js.erb
<% if @comment.errors.any? %>
  $("#comment-notice").html('<div class="alert"><%= escape_javascript(alert) %></div>');
  <% flash.delete(:alert) %>
<% else %>
  $("#comment-alert").hide(300);
  $(":input:not(input[type=submit])").val("");
  $('.comments-list').prepend("<%= escape_javascript(render 'comment', { :comment => @comment })%>")
    $("#comment-notice").html('<div class="notice"><%= escape_javascript(notice) %></div>');
    <% flash.delete(:notice) %>
<% end %>

app/views/comments/destroy.js.erb
var div = $("#comment_<%= @comment_id -%>");

div.fadeOut('slow', function(){
  div.remove();
});

app/views/comments/edit.js.erb
$('#comment_<%= @comment.id -%>').html("<%= escape_javascript(render 'form')%>")

app/views/comments/new.js.erb
$('.comment-post-container').html("<%= escape_javascript(render 'form')%>")

app/views/comments/update.js.erb
<% if @comment.errors.any? %>
  $("#comment-notice").html('<div class="alert"><%= escape_javascript(alert) %></div>');
  <% flash.delete(:alert) %>
<% else %>
  $("#comment-alert").hide(300);
  $(":input:not(input[type=submit])").val("");
  $("#comment_<%= @comment.id -%>").replaceWith("<%= escape_javascript(render 'comment', { :comment => @comment })%>");
  $("#comment-notice").html('<div class="notice"><%= escape_javascript(notice) %></div>');
  <% flash.delete(:notice) %>
<% end %>