config/routes.rb
MapEverything::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }, :path_prefix => 'd', :sign_out_via => [ :get, :post, :delete ]

  get '/feed' => 'features#feed',
    :as => :feed,
    :defaults => { :format => 'atom' },
    :show_unapproved => false

  get '/moderator_feed' => 'features#feed',
    :as => :moderator_feed,
    :defaults => { :format => 'atom' },
    :show_unapproved => true

  get 'features/map' => 'features#map', :as => 'map'
  match 'features/:id/toggle_like/:vote' => 'features#toggle_like'
  get 'features/:id/like_widget' => 'features#like_widget'
  resources :features do
  end

  resources :comments
  resources :users

  root :to => "features#map"

end

app/models/feature.rb
# encoding: utf-8

class Feature < ActiveRecord::Base

  belongs_to :user
  has_and_belongs_to_many :users_liked, :join_table => :features_users_likes, :class_name => 'User'

  attr_accessible :geometry, :name, :description, :capacity, :comment
  attr_accessible :photo, :existing, :approved, :address

  has_attached_file :photo,
    :styles => {:large => "800x600",
      :medium => "640x480>",
      :thumb => "100x100"
    }

  validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }

  validates :description, :presence => true
  validates :geometry, :presence => true

  set_rgeo_factory_for_column(:latlon, RGeo::Geographic.spherical_factory(:srid => 4326))
  RGeo::ActiveRecord::GeometryMixin.set_json_generator(:geojson)

  comma do
    geometry I18n.t('feature.coordinates')
    existing I18n.t('feature.type') do |existing| existing ? I18n.t('feature.existing') : I18n.t('feature.needed') end
    rating I18n.t('feature.rating')
    description I18n.t('feature.description')
    address I18n.t('feature.address')
    comment I18n.t('feature.comment')
    capacity I18n.t('feature.capacity')
    approved I18n.t('feature.approved') do |approved| approved ? I18n.t('yes') : I18n.t('no') end
    created_at I18n.t('feature.created_at')
    user I18n.t('feature.user') do |user| user.name end
  end


  def as_json(params)
    properties = self.attributes.dup
    properties.delete('geometry')
    hash = {:type => 'Feature', :geometry => self.geometry, :properties => properties}
    hash.as_json
  end

  def self.from_json(params)
    f = self.new
    coordinates = params["geometry"]["coordinates"]
    f.geometry = "POINT(#{coordinates[0]} #{coordinates[1]})"
    logger.debug "from_json: "
    logger.debug f.geometry.inspect

    unless params["properties"].nil?
      params["properties"].each_pair do |key, val|
        f.send(key+'=', val)
      end
    end

    f
  end

  def toggle_like(user, vote)
    transaction do
      if self.users_liked.include? user
        if vote == 'dislike'
          self.users_liked.delete user
          self.rating -= 1
        end
      else
        if vote == 'like'
          self.users_liked << user
          self.rating += 1
        end
      end
      self.save
    end
  end

  def liked_by?(user)
    self.users_liked.include? user
  end

end

app/controllers/features_controller.rb
# encoding: utf-8

class FeaturesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show, :map, :feed]
  helper_method :have_edit_permissions?
  helper_method :sort_column, :sort_direction, :show_existing

  private
  def have_edit_permissions?(feature)
    return false if current_user.nil?
    current_user.admin? or feature.user == current_user
  end

  public

  # GET /features
  # GET /features.json
  def index
    if !user_signed_in?
      @features = Feature.where(:approved => true)
    else
      if current_user.admin?
        @features = Feature.where('')
      else
        @features = Feature.where('approved = ? OR user_id = ?', true, current_user.id)
      end
    end

    respond_to do |format|
      format.html {
        params[:sort] ||= 'rating'
        params[:direction] ||= 'desc'
        @features = @features.where(:existing => show_existing)
        @features = @features.order(sort_column + ' ' + sort_direction)
      } # index.html.erb

      format.json {
        feature_collection = {:type => 'FeatureCollection', :features => @features}
        render json: feature_collection
      }
      format.csv { render csv: @features, :filename => 'bikeparkings' }
    end
  end

  def feed
    if params[:show_unapproved]
      @title = t('features.moderators_map')
      @features = Feature.order('created_at DESC')
    else
      @title = t('features.latest_map')
      @features = Feature.where(:approved => true).order('created_at DESC')
    end

    @updated = @features.first.updated_at unless @features.empty?

    respond_to do |format|
      format.rss { redirect_to feed_path(:format => :atom), :status => :moved_permanently }
      format.atom
    end
  end

  # GET /features/1
  # GET /features/1.json
  def show
    @feature = Feature.find(params[:id])
    @title = @feature.existing? ? t('features.bikeparking') : t('features.bikeparking_needed')
    @liked = @feature.users_liked.include? current_user if user_signed_in?

    respond_to do |format|
      format.html {render :layout => 'feature-popup'}
      format.json { render json: @feature }
      format.js
    end
  end

  # GET /features/new
  # GET /features/new.json
  def new
    @title = t('features.new')
    @subtitle = t('features.new_subtitle')
    @hide_like = true
    @feature = Feature.new
    @feature.geometry = params[:geometry]
    @feature.user = current_user

    respond_to do |format|
      format.html {render :layout => 'feature-popup'}
      format.json { render json: @feature }
      format.js
    end
  end

  # GET /features/1/edit
  def edit
    @title = t('features.edit')
    @hide_like = true
    @feature = Feature.find(params[:id])
    respond_to do |format|
      format.html {render :layout => 'feature-popup'}
      format.js
    end
  end

  # POST /features
  # POST /features.json
  def create
    if request.format == 'application/json'
      @feature = Feature.from_json(params)
    else
      @feature = Feature.new(params[:feature])
    end

    @feature.user = current_user

    respond_to do |format|
      if @feature.save
        @feature.toggle_like(current_user, 'like')
        format.html { redirect_to @feature, notice: t('feature.created') }
        format.json { render json: @feature, status: :created, location: @feature }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
        format.js { render action: 'new' }
      end
    end
  end

  # PUT /features/1
  # PUT /features/1.json
  def update
    attrs = {}
    if request.format == 'application/json'
      @feature = Feature.find(params["properties"][:id])
      attrs = params["properties"]
      attrs.merge!("geometry" => params["geometry"])
    else
      @feature = Feature.find(params[:id])
      attrs = params[:feature] if params[:feature]
    end

    if params[:remove_photo]
      @feature.photo = nil
    end

    respond_to do |format|
      if !attrs["geometry"].nil? and !attrs["geometry"]["coordinates"].nil?
        coords = attrs["geometry"]["coordinates"]
        attrs['geometry'] = "POINT(#{coords[0]} #{coords[1]})"
      end
      
      if have_edit_permissions?(@feature) and @feature.update_attributes(attrs)
        format.html { redirect_to @feature, notice: t('features.updated') }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "edit", layout: 'feature-popup' }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
        format.js { render action: 'edit' }
      end
    end
  end

  def toggle_like
    respond_to do |format|
      begin

        @feature = Feature.find(params[:id])

        @feature.toggle_like(current_user, params[:vote])

        format.json {render json: @feature.rating}
        format.js
      rescue
        format.json {render status: :unprocessable_entity}
      end
    end
  end

  def like_widget
    @feature = Feature.find(params[:id])

    respond_to do |format|
      format.html {render :partial => 'like_widget'}
    end
  end

  # DELETE /features/1
  # DELETE /features/1.json
  def destroy
    @feature = Feature.find(params[:id])
    respond_to do |format|
      if have_edit_permissions?(@feature)
        @feature.destroy

        format.html { redirect_to features_url }
        format.json { head :no_content }
        format.js
      else
        format.json { render status: :unprocessable_entity }
        format.html { redirect_to features_url, :alert => t('features.no_permissions') }
        format.js { render action: 'edit' }
      end
    end
  end

  def map
    @existing_features = Feature.where(:approved => true).where(:existing => true).order('created_at DESC')
    @desired_features = Feature.where(:approved => true).where(:existing => false).order('created_at DESC')
    @not_approved_features = Feature.where(:approved => false)
    @latest_comments = Comment.page(params[:comments_page]).order('posted_on DESC')
    render
  end

  private

  def sort_column
    Feature.column_names.include?(params[:sort]) ? params[:sort] : "rating"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

  def show_existing
    (params[:existing] == 'false') ? false : true
  end

end

app/helpers/features_helper.rb
module FeaturesHelper
  def get_likebutton_img(type, enabled)
    case type
    when 'like'
      img = 'plus'
    when 'dislike'
      img = 'minus'
    end
    img += '-disabled' unless enabled
    img += '-24px.png'
    img
  end

  def sortable(column, title = nil)
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction, :existing => show_existing }, {:class => css_class}
  end

  def link_to_existing(title, existing)
    css_class = (existing == show_existing) ? 'active' : nil
    link_to title, {:sort => sort_column, :direction => sort_direction, :existing => existing}, {:class => css_class}
  end
end

app/views/features/_features-list.html.erb
<table>
  <tr>
    <th>№</th>
    <% if show_photo %>
      <th>Фото</th>
    <% end %>
    <th><%= sortable 'description', 'Название места' %></th>
    <th><%= sortable 'address', 'Адрес' %></th>
    <th><%= sortable 'rating', 'Рейтинг' %></th>
    <th><%= sortable 'comment', 'Комментарий' %></th>
    <th><%= sortable 'created_at', 'Дата добавления' %></th>
    <th><%= sortable 'user_id', 'Автор' %></th>
    <th>Ссылка</th>
  </tr>

  <% i = 1 %>
<% features.each do |feature| %>
  <% next unless feature.approved? %>
  <tr>
    <td><%= i %></td>
    <% if show_photo %>
      <td><%= link_to image_tag(feature.photo.url(:thumb)), feature.photo.url(:large), :rel => "lightbox", :title => feature.description  unless feature.photo_file_name.nil? %><br/>
        <%= link_to t('.original_img_size'), feature.photo.url unless feature.photo_file_name.nil? %></td>
    <% end %>
    <td><%=feature.description %></td>
    <td><%=feature.address unless feature.address.blank? %></td>
    <td><%= feature.rating %></td>
    <td><%= feature.comment %></td>
    <td><%= feature.created_at.to_date %></td>
    <% if user_signed_in? and current_user.admin? then -%>
      <td><%= link_to feature.user.name, user_path(feature.user) unless feature.user.nil? %></td>
    <% else %>
      <td><%= feature.user.name unless feature.user.nil? %></td>
    <% end %>
    <td><%= link_to '→', map_url + "?feature=#{feature.id}", :title => 'Карта' %></td>
  </tr>
  <% i += 1 %>
<% end %>
</table>

<br />

app/views/features/_form.html.erb
<% if @feature.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @feature.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @feature, :remote => true do |f| %>
  <%= f.hidden_field :geometry unless @feature.geometry.nil? %>
  <div class="field mandatory">
    <%= f.label :description, 'Название места:' %><br/>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :address, 'Адрес:' %><br/>
    <%= f.text_field :address %>
  </div>
    <% unless @feature.photo_file_name.nil? %>
  <div class="field">
    <%= link_to image_tag(@feature.photo.url(:thumb)), @feature.photo.url(:large), :rel => "lightbox", :title => @feature.description %>
      <%= check_box_tag 'remove_photo' %>
      <%= label_tag 'remove_photo', 'Удалить фото' %>
  </div>
  <% end %>
  <div class="field<%= " hidden" unless @feature.existing? -%>" id="photo">
    <%= f.label :photo, 'Загрузить фото:' %><br/>
    <%= f.file_field :photo %>
  </div>
  <!--
  <div class="field">
    <%= f.label :capacity, 'Ёмкость:' %>
    <%= f.number_field :capacity, :min => 1, :size => 3 %>
  </div>
  -->
  <div class="field">
    <%= f.label :comment, 'Комментарий:' %><br/>
    <%= f.text_field :comment %>
  </div>
  <% if !current_user.nil? and current_user.admin? %>
  <!--
    <div class="field">
      <%= f.check_box :approved %>
      <%= f.label :approved, 'Одобрено' %>
    </div>
    -->
  <% end %>
  <div class="submit">
    <%= f.submit 'Сохранить' %>
    <%= f.submit 'Отмена', :class => 'cancel' %>
    <%= link_to 'Удалить', '#', :class => 'feature-del-link', :remote => true, :method => :delete unless @feature.id.nil? %>
  </div>
<% end %>

app/views/features/_like_widget.html.erb
<h5>Рейтинг:</h5>
<% if @feature.approved? %>
  <% unless current_user.nil? %>
    <a href="#" rel="nofollow" id="feature-popup-dislike" class="feature-rating"><%= image_tag get_likebutton_img('dislike', @feature.liked_by?(current_user)) -%></a>
  <% end %>
  <span id="feature-popup-rating" class="feature-rating"><%= @feature.rating -%></span>
  <% unless current_user.nil? %>
    <a href="#" rel="nofollow" id="feature-popup-like" class="feature-rating"><%= image_tag get_likebutton_img('like', !@feature.liked_by?(current_user)) -%></a>
  <% end %>
<% else %>
  Точка станет доступной для голосования после проверки модератором.
<% end %>

app/views/features/destroy.js.erb
theMap.closePopup();
theCustomMap.removeFeature(<%= @feature.id -%>); 

app/views/features/edit.html.erb
<% content_for :navigation do %>
<% end %>

<%= render 'form' %>

app/views/features/edit.js.erb
feature = theCustomMap._selectedFeature;

feature.bindPopup("<%= escape_javascript(render :file => 'features/edit', :layout => 'layouts/feature-popup', :formats => [:html])%>");
feature.closePopup();
feature.openPopup();

$('input.cancel').click(function(e) {
  theMap.closePopup();
  return false;
});

$('.feature-del-link').click(function(e) {
  $.ajax({    url: '/features/' + feature.properties.id,
    type: 'DELETE',
    dataType: 'script',
  });
  return false;
});


$('a[rel*="lightbox"]').lightBox();

$('input[name="feature[existing]"]').click(function(e) {
  $('.field#photo').toggle($('#feature_existing_true')[0].checked);
});

app/views/features/index.html.erb
<h2>Список мест</h2>


<%= render :partial => 'features-list', :locals => { :features => @features, :show_photo => true } %>

<%= link_to 'Скачать как CSV', features_path(:format => 'csv') if admin_logged_in? %>

app/views/features/map.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag    "leaflet", :media => "all" %>
  <!--[if lte IE 8]><%= stylesheet_link_tag "leaflet.ie", :media => "all" %><![endif]-->
  <%= javascript_include_tag "leaflet" %>
  <%= javascript_include_tag "features-map" %>
<% end %>

<% unless current_user.nil? %>
  <%= tag 'div', { id: 'current-user', data: {uid: current_user.id, admin: current_user.admin?, name: current_user.name} }, true %></div>
<% end %>

<div> Для добавления точек войдите на сайт. Точки добавляются простым кликом по карте при максимальном приближении (клик на других масштабах приблизит карту до максимального уровня).</div>
<div id="map" style="height: 600px; width: 100%;" data-center-lat="<%= Rails.application.config.map_center_lat -%>" data-center-lon="<%= Rails.application.config.map_center_lon -%>" data-zoom="<%= Rails.application.config.map_zoom -%>" /></div>


<% content_for :left do %>
  <div class="custom-block">
    <h3>Парковки</h3>
  <ul class="tabs-nav">
    <li><a href="#tab-existing">Существующие</a></li>
    <li><a href="#tab-desired">Желаемые</a></li>
    <% if admin_logged_in? %>
      <li><a href="#tab-nonapproved">На модерацию</a></li>
    <% end %>
  </ul>

  <% if !current_user.nil? and current_user.admin? %>
    <div class="tabs-panel top-features" id="tab-nonapproved">
      <ul>
        <% @not_approved_features.each do |feature| %>
          <li class="feature">
          <a href="#" class="feature-top-item" id="feature_top_item_<%= feature.id -%>">
            <div class="feature-list-icon leaflet-div-icon-<%= feature.existing? ? 'existing' : 'desired' -%> <%= 'feature-notapproved' unless feature.approved? %>"><strong><%= feature.rating %></strong></div>
            <%= feature.description %>
          </a>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="tabs-panel top-features" id="tab-existing">
    <ul>
      <% @existing_features.each do |feature| %>
        <li class="feature">
        <a href="#" class="feature-top-item" id="feature_top_item_<%= feature.id -%>">
          <div class="feature-list-icon leaflet-div-icon-existing <%= 'feature-notapproved' unless feature.approved? %>"><strong><%= feature.rating %></strong></div>
          <%= feature.description %>
        </a>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="tabs-panel top-features" id="tab-desired">
    <ul>
      <% @desired_features.each do |feature| %>
        <li class="feature">
        <a href="#" class="feature-top-item" id="feature_top_item_<%= feature.id -%>">
          <div class="feature-list-icon leaflet-div-icon-desired <%= 'feature-notapproved' unless feature.approved? %>"><strong><%= feature.rating %></strong></div>
          <%= feature.description %>
        </a>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>


<% content_for :bottom do %>
  <div id="comments-latest" class="comments-latest custom-block">
    <h3>Комментарии</h3>
    <div class="comment-post-container">
      <%= link_to 'Комментировать', new_comment_path, :remote => true if user_signed_in? %>
    </div>
    <ul class="comments-list">
      <% @latest_comments.each do |comment| %>
        <%= render :file => 'comments/_comment', :locals => { :comment => comment } %>
      <% end %>
    </ul>
      <%= will_paginate @latest_comments, :param_name => :comments_page %>
  </div>
<% end %>

app/views/features/new.html.erb
<% content_for :navigation do %>
<% end %>

<%= render 'form' %>

app/views/features/new.js.erb
feature = theCustomMap._selectedFeature;

feature.bindPopup("<%= escape_javascript(render :file => 'features/new', :layout => 'layouts/feature-popup', :formats => [:html])%>");
feature.closePopup();
feature.openPopup();

$('input.cancel').click(function(e) {
  feature.closePopup();
  theCustomMap.removeLayer(feature);
  return false;
});

$('#feature-popup-like').click(function(e) {
  theCustomMap.toggleLike(feature);
});

$('a[rel*="lightbox"]').lightBox();

$('input[name="feature[existing]"]').click(function(e) {
  $('.field#photo').toggle($('#feature_existing_true')[0].checked);
});

app/views/features/show.html.erb
<% if have_edit_permissions?(@feature) %>
  <div id="feature-popup-nav"><a id="edit-link">Редактировать</a></div>
<% end %>

<p><%= @feature.description %></p>
<% unless @feature.address.blank? %>
  <p><%= @feature.address %></p>
<% end %>

<% unless @feature.photo_file_name.nil? %> 
  <p>
  <%= link_to image_tag(@feature.photo.url(:thumb)), @feature.photo.url(:large), :rel => "lightbox", :title => @feature.description  unless @feature.photo_file_name.nil? %>
  </p>
<% end %>

<!--<div>
  <strong>Ёмкость:</strong>
  <%= @feature.capacity %>
</div>-->
<% unless @feature.comment.blank? %>
  <p>
  <%= @feature.comment %>
  </p>
<% end %>
<p>
  <strong><%= @feature.user.nil? ? 'Аноним' : @feature.user.name %></strong> <%= @feature.created_at.strftime('%d.%m.%Y') %>
</p>

app/views/features/show.js.erb
feature = theCustomMap._selectedFeature;

feature.bindPopup("<%= escape_javascript(render :file => 'features/show', :layout => 'layouts/feature-popup', :formats => [:html])%>");
feature.closePopup();
feature.openPopup();

$('#feature-popup-like').click(function(e) {
  theCustomMap.toggleLike(feature, "<%= 'like' -%>");
});

$('#feature-popup-dislike').click(function(e) {
  theCustomMap.toggleLike(feature, "<%= 'dislike' -%>");
});

$('#edit-link').click(function(e) {
  $.ajax({
    url: '/features/' + feature.properties.id + '/edit',
    type: 'GET',
    dataType: 'script',
  });
});

$('a[rel*="lightbox"]').lightBox();

app/views/features/toggle_like.js.erb
$('#like_widget').html("<%= escape_javascript render 'like_widget' %>")
$('#feature-popup-like').click(function(e) {
  theCustomMap.toggleLike(null, "<%= escape_javascript 'like' -%>");
});

$('#feature-popup-dislike').click(function(e) {
  theCustomMap.toggleLike(null, "<%= escape_javascript 'dislike' -%>");
});

app/views/features/update.js.erb
theCustomMap.reloadFeature(<%= @feature.id %>);