config/routes.rb
MapEverything::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }, :path_prefix => 'd', :sign_out_via => [ :get, :post, :delete ]

  get '/feed' => 'features#feed',
    :as => :feed,
    :defaults => { :format => 'atom' },
    :show_unapproved => false

  get '/moderator_feed' => 'features#feed',
    :as => :moderator_feed,
    :defaults => { :format => 'atom' },
    :show_unapproved => true

  get 'features/map' => 'features#map', :as => 'map'
  match 'features/:id/toggle_like/:vote' => 'features#toggle_like'
  get 'features/:id/like_widget' => 'features#like_widget'
  resources :features do
  end

  resources :comments
  resources :users

  root :to => "features#map"

end

app/views/layouts/_feature-popup.html.erb
<div id="feature-popup-header">
  <img src="/assets/marker-icon.png"/>
  <span id="feature-popup-like" class="feature-rating">Like</span>
  <span id="feature-popup-rating" class="feature-rating"><%= @feature.rating -%></span>
  <span id="feature-popup-dislike" class="feature-rating">Dislike</span>
</div>
<div id="feature-popup-contents">

  <% unless notice.nil? %>
    <p class="notice"><%= notice %></p>
  <% end -%>

  <% unless alert.nil? %>
    <p class="alert"><%= alert %></p>
  <% end -%>

  <%= yield %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Карта велопарковок</title>
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "blueprint/screen", :media => "screen" %>
  <%= stylesheet_link_tag    "blueprint/print", :media => "print" %>
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>

  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag controller_name unless MapEverything::Application.assets.find_asset("#{controller_name}.js").nil?  %>

  <%= yield :head %>

  <%= stylesheet_link_tag  controller_name, :media => "all" unless MapEverything::Application.assets.find_asset("#{controller_name}.css").nil? %>

  <%= auto_discovery_link_tag :atom, "/feed" %>
  <%= auto_discovery_link_tag :rss, "/feed.rss" %>
</head>
<body>

  <div class="container">
    <div id="header" class="full-width">
      <nav id="secondary">
      <ul>
        <li><%= link_to "Список парковок", features_path %></li>
      </ul>
      </nav>

    <nav id="main">
      <ul>
        <% unless action_name == "map" %>
          <li><%= link_to "Карта", map_path %></li>
        <% end %>
        <% if user_signed_in? -%>
          <% if current_user.admin? %>
            <li><%= link_to "Пользователи", users_path %></li>
          <% end %>
          <li><%= link_to_user current_user %></li>
          <li><%= link_to "Выйти", destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to "Войти", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>

    <%= yield(:header) %>
  </div>

    <div id="center">
      <% unless notice.nil? %>
        <p class="notice"><%= notice %></p>
      <% end %>
      <% unless alert.nil? %>
        <p class="alert"><%= alert %></p>
      <% end %>


      <%= yield %>
    </div>

    <div id="left">
      <%= yield(:left) %>
    </div>

    <div id="right">
      <%= yield(:bottom) %>
    </div>

  <div id="footer" class="full-width">
    <p>
    <%= link_to feed_path do
      image_tag('feed.png', :class => 'link-icon') + ' RSS'
    end %><br/>
    <%= link_to moderator_feed_path do
      image_tag('feed.png', :class => 'link-icon') + ' RSS — модераторское'
    end  if user_signed_in? and current_user.admin? %>
    </p>
    <%= yield(:footer) %>
  </div>
  </div>


</body>
</html>

app/views/layouts/feature-popup.html.erb
<div id="feature-popup-header">
  <% unless @title.nil? %>
    <h3 id="popup-title"><%= @title %></h3>
  <% end %>
  <% unless @subtitle.nil? %>
    <h4 id="popup-subtitle"><%= @subtitle %></h4>
  <% end %>
</div>
<div id="feature-popup-contents">

  <% unless notice.nil? %>
    <p class="notice"><%= notice %></p>
  <% end -%>

  <% unless alert.nil? %>
    <p class="alert"><%= alert %></p>
  <% end -%>

  <%= yield %>
  <% unless @hide_like %>
    <div id="like_widget">
      <%= render 'like_widget' %>
    </div>
  <% end %>
</div>